apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "stream-base64-webcam.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "stream-base64-webcam.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stream-base64-webcam.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
          hostPort: 9110
          name: video
          protocol: TCP
        securityContext:
            privileged: true
