apiVersion: v1
kind: Service
metadata:
  name: {{ include "stream-base64-webcam.fullname" . }}
  labels:
    {{- include "stream-base64-webcam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "stream-base64-webcam.selectorLabels" . | nindent 4 }}